CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(256) NOT NULL,
	[Type] INTEGER NOT NULL,

	[Pz] BIT NOT NULL,
	[Lz] BIT NOT NULL,
	[L] BIT NOT NULL,
	[Prepod1] VARCHAR(128) NOT NULL,
	[Prepod2] VARCHAR(128) NULL,
	[Prepod3] VARCHAR(128) NULL,
	[Prepod4] VARCHAR(128) NULL,
)
